name: Build and Deploy Package

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install --dev

      - name: Run tests with coverage
        run: pipenv run pytest --cov=src --cov-report=term-missing --cov-fail-under=80 --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4

      - name: Build wheel
        run: pipenv run python3 -m build

      - name: Upload to remote
        run: pipenv run twine upload --repository-url https://upload.pypi.org/legacy/ dist/*