name: Run Python Tests

on:
  pull_request:
    branches: [main]

jobs:
  run-python-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install --dev

      - name: Run tests with coverage
        run: pipenv run pytest --cov=src --cov-report=term-missing --cov-fail-under=80 --cov-report=xml

      - name: Check release number
        run: pipenv run python .github/scripts/release_candidate.py